URL = {
    'getCode':{#获取验证码
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/sys/getCode',
                'method':'GET',
                'refer':'https://study.jxgbwlxy.gov.cn/index',
            },
    'login':{#登录
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/sys/login',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/index',
            },
    'online':{#获取分数
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/report/myData/online',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/study/data',
            },
    'findCoursewareById':{#查找课程
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/study/platform/platformCourseware/findCoursewareById',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/courseDetailsNew?',
            },
    'annualPortalCourseListNew':{#我的必修课
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/study/years/yearsCourseware/annualPortalCourseListNew',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/study/courseMine?id=0',
            },
    'myElectivesNew':{#我的选修课
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/study/my/elective/myElectivesNew',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/study/courseMine?id=0',
            },
    'courseOverview':{#课程总览
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/study/platform/platformCourseware/courseOverview',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/study/course-view',
            },
    'joinIn':{#加入选课
                'requestUrl':'https://study.jxgbwlxy.gov.cn/api/study/my/elective/joinIn',
                'method':'POST',
                'refer':'https://study.jxgbwlxy.gov.cn/study/course-view',
            },
    'video':{#课程视频页
                'requestUrl':'https://study.jxgbwlxy.gov.cn/video?',
                'method':'POST',
                'refer':'',
            },
 }

